ARG PARENT_IMAGE

FROM $PARENT_IMAGE

MAINTAINER fabien.sanglier@softwareaggov.com

ARG SAG_HOME
ARG MSC_INSTANCE_NAME

ENV PACKAGES_HOME=$SAG_HOME/IntegrationServer/instances/${MSC_INSTANCE_NAME}/packages

COPY wMPackages/WxConsulHelper.zip $PACKAGES_HOME/WxConsulHelper/WxConsulHelper.zip
COPY wMPackages/WxIPLocator.zip $PACKAGES_HOME/WxIPLocator/WxIPLocator.zip
RUN yum install -y unzip && \
unzip $PACKAGES_HOME/WxConsulHelper/WxConsulHelper.zip -d $PACKAGES_HOME/WxConsulHelper/ && \
rm -f $PACKAGES_HOME/WxConsulHelper/WxConsulHelper.zip && \
unzip $PACKAGES_HOME/WxIPLocator/WxIPLocator.zip -d $PACKAGES_HOME/WxIPLocator/ && \
rm -f $PACKAGES_HOME/WxIPLocator/WxIPLocator.zip && \
yum remove -y unzip