version: "3.0"

networks:
  sagdemodev:

services:

  msc1:
    image: ${REGISTRY}custom/softwareag/webmethods-microservicescontainer:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.msc.custom
      args:
        SAG_HOME: ${SAG_HOME}
    networks:
      - sagdemodev
    volumes: 
      - ./replicate:${SAG_HOME}/IntegrationServer/instances/default/replicate
      - ./msc_consul_config_registry.cnf:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
    ports:
      - "5555:5555"
    depends_on:
      - consul-server-bootstrap

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - sagdemodev
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"