FROM custom/softwareag/webmethods-microservicescontainer:10.1

MAINTAINER fabien.sanglier@softwareaggov.com

ENV SAG_HOME=/sag
ENV INSTANCE_NAME=default
ENV PACKAGES_HOME=$SAG_HOME/IntegrationServer/instances/${INSTANCE_NAME}/packages

COPY wMPackages/WxUserService.zip $PACKAGES_HOME/WxUserService/WxUserService.zip
RUN yum install -y unzip && \
unzip $PACKAGES_HOME/WxUserService/WxUserService.zip -d $PACKAGES_HOME/WxUserService/ && \
rm -f $PACKAGES_HOME/WxUserService/WxUserService.zip && \
yum remove -y unzip