#FROM store/softwareag/webmethods-microservicescontainer:10.1
FROM registry.docker.tests:5000/softwareag/msc:10.1

MAINTAINER fabien.sanglier@softwareaggov.com

ARG SAG_HOME

### ADD license key
COPY licenseKey.xml $SAG_HOME/IntegrationServer/instances/default/config/licenseKey.xml

### ADD consul registry info
COPY msc_consul_config_registry.cnf $SAG_HOME/IntegrationServer/instances/default/config/microservices/registry.cnf