FROM custom/softwareag/webmethods-microservicescontainer:10.1

MAINTAINER fabien.sanglier@softwareaggov.com

ENV SAG_HOME=/sag
ENV INSTANCE_NAME=default
ENV PACKAGES_HOME=$SAG_HOME/IntegrationServer/instances/${INSTANCE_NAME}/packages

COPY wMPackages/WxUserInfo.zip $PACKAGES_HOME/WxUserInfo/WxUserInfo.zip
RUN yum install -y unzip && \
unzip $PACKAGES_HOME/WxUserInfo/WxUserInfo.zip -d $PACKAGES_HOME/WxUserInfo/ && \
rm -f $PACKAGES_HOME/WxUserInfo/WxUserInfo.zip && \
yum remove -y unzip