ARG PARENT_IMAGE

FROM $PARENT_IMAGE

MAINTAINER fabien.sanglier@softwareaggov.com

ARG SAG_HOME
ARG MSC_INSTANCE_NAME

### ADD license key -- use embedded trial
##COPY licenseKey.xml $SAG_HOME/IntegrationServer/instances/${MSC_INSTANCE_NAME}/config/licenseKey.xml

### ADD consul registry info
COPY msc_consul_config_registry.cnf $SAG_HOME/IntegrationServer/instances/${MSC_INSTANCE_NAME}/config/microservices/registry.cnf