version: "3.0"

networks:
  sagdemo:

services:

  userservice_1:
    image: ${REGISTRY}softwareag/userservice:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.userservice
    networks:
      - sagdemo
    ports:
      - "5556:5555"
    depends_on:
      - consul-server-bootstrap

  iplocator_1:
    image: ${REGISTRY}softwareag/iplocator:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.iplocator
    networks:
      - sagdemo
    ports:
      - "5557:5555"
    depends_on:
      - consul-server-bootstrap

  userinfo_1:
    image: ${REGISTRY}softwareag/userinfo:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.userinfo
    networks:
      - sagdemo
    ports:
      - "5558:5555"
    depends_on:
      - consul-server-bootstrap

  fibonacci_1:
    image: ${REGISTRY}softwareag/fibonacci:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
    networks:
      - sagdemo
    ports:
      - "5559:5555"
    depends_on:
      - consul-server-bootstrap

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - sagdemo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"