version: "3.0"

networks:
  sagdemoruntime:
    external: true

services:

  msc_apimashup_userfull_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_apimashup_userfull:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.apimashup.userfull
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5556:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul
      - msc_iplocator_1
      - msc_userinfo_1
      - msc_fibonacci_1

  msc_iplocator_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_iplocator:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.iplocator
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5557:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul

  msc_userinfo_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_userinfo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userinfo
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5558:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul
      - msc_randomutils_1

  msc_fibonacci_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_fibonacci:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5559:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul

  msc_randomutils_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_randomutils:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.randomutils
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5560:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul

  consul:
    image: consul:1.2.3
    command: "agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn"
    networks:
      sagdemoruntime:
        aliases:
          - consul.test
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"