version: "3.0"

networks:
  sagdemodev:
    external: true

services:
  microapigateway_userservice:
    image: store/softwareag/microgateway-trial:${TAG}
    environment:
      - apigw_url=http://apigateway:5555/rest/apigateway
      - apigw_user=Administrator
      - apigw_password=manage
      - apis=userdetails
    networks:
      - sagdemodev
    ports:
      - "9090:4485"
    depends_on:
      - apigateway

  microapigateway_userinfo:
    image: store/softwareag/microgateway-trial:${TAG}
    environment:
      - apigw_url=http://apigateway:5555/rest/apigateway
      - apigw_user=Administrator
      - apigw_password=manage
      - apis=userinfo
    networks:
      - sagdemodev
    ports:
      - "9091:4485"
    depends_on:
      - apigateway

  microapigateway_iplocator:
    image: store/softwareag/microgateway-trial:${TAG}
    environment:
      - apigw_url=http://apigateway:5555/rest/apigateway
      - apigw_user=Administrator
      - apigw_password=manage
      - apis=iplocator
    networks:
      - sagdemodev
    ports:
      - "9092:4485"
    depends_on:
      - apigateway

  microapigateway_fibonacci:
    image: store/softwareag/microgateway-trial:${TAG}
    environment:
      - apigw_url=http://apigateway:5555/rest/apigateway
      - apigw_user=Administrator
      - apigw_password=manage
      - apis=fibonacci
    networks:
      - sagdemodev
    ports:
      - "9093:4485"
    depends_on:
      - apigateway

  apigateway:
    image: store/softwareag/apigateway-trial:${TAG}
    ports:
      - "5555:5555"
      - "9072:9072"
    networks:
      sagdemodev:
        aliases:
          - apigateway.docker.tests

  mscdev:
    image: store/softwareag/webmethods-microservicesruntime:${TAG}
    networks:
      sagdemodev:
        aliases:
          - fibonacci.clouddemo.saggov.com
          - iplocator.clouddemo.saggov.com
          - userinfo.clouddemo.saggov.com
          - userdetails.clouddemo.saggov.com
          - randomutils.clouddemo.saggov.com
    volumes:
      - ./work/replicate/:${SAG_HOME}/IntegrationServer/instances/default/replicate/
      - ./assets/IS/Packages/WxAPIClientUtils/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxAPIClientUtils/
      - ./assets/IS/Packages/WxAPIMashupUserFull/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxAPIMashupUserFull/
      - ./assets/IS/Packages/WxUserInfo/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxUserInfo/
      - ./assets/IS/Packages/WxRandomUtils/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxRandomUtils/
      - ./assets/IS/Packages/WxIPLocator/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxIPLocator/
      - ./assets/IS/Packages/WxFibonacci/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxFibonacci/
      - ./assets/IS/Packages/WxUserInfoClient/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxUserInfoClient/
      - ./assets/IS/Packages/WxRandomUtilsClient/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxRandomUtilsClient/
      - ./assets/IS/Packages/WxIPLocatorClient/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxIPLocatorClient/
      - ./assets/IS/Packages/WxFibonacciClient/:${SAG_HOME}/IntegrationServer/instances/default/packages/WxFibonacciClient/
      - ./assets/IS/Configs/Dev/registry.xml:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
      - ./assets/IS/Configs/Dev/globalVariables.xml:${SAG_HOME}/IntegrationServer/instances/default/config/globalVariables.cnf
      - ./assets/IS/Configs/Dev/application.properties:${SAG_HOME}/IntegrationServer/instances/default/application.properties
    ports:
      - "5555:5555"
    depends_on:
      - consul-dev

  consul-dev:
    image: consul:1.2.3
    command: "agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn"
    networks:
      sagdemodev:
        aliases:
          - consul.test
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"