version: "3.0"

networks:
  sagdemoruntime:

services:

  userservice_1:
    image: custom/softwareag/msc-userservice:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userservice
      args:
        PARENT_IMAGE: ${REGISTRY}/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    volumes:
      - ./msc_consul_config_registry.cnf:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
    ports:
      - "5556:5555"
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  iplocator_1:
    image: custom/softwareag/msc-iplocator:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.iplocator
      args:
        PARENT_IMAGE: ${REGISTRY}/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    volumes:
      - ./msc_consul_config_registry.cnf:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
    ports:
      - "5557:5555"
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  userinfo_1:
    image: custom/softwareag/msc-userinfo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userinfo
      args:
        PARENT_IMAGE: ${REGISTRY}/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    volumes:
      - ./msc_consul_config_registry.cnf:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
    ports:
      - "5558:5555"
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  fibonacci_1:
    image: custom/softwareag/msc-fibonacci:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
      args:
        PARENT_IMAGE: ${REGISTRY}/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    volumes:
      - ./msc_consul_config_registry.cnf:${SAG_HOME}/IntegrationServer/instances/default/config/microservices/registry.cnf
    ports:
      - "5559:5555"
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - sagdemoruntime
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"