version: "3.0"

services:

  msc_custom:
    image: custom/softwareag/webmethods-microservicesruntime:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.msc.custom
      args:
        PARENT_IMAGE: ${REGISTRY}/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default

  iplocator:
    image: custom/softwareag/msc-iplocator:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.iplocator
      args:
        PARENT_IMAGE: custom/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    depends_on:
      - msc_custom

  userinfo:
    image: custom/softwareag/msc-userinfo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userinfo
      args:
        PARENT_IMAGE: custom/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    depends_on:
      - msc_custom

  userservice:
    image: custom/softwareag/msc-userservice:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userservice
      args:
        PARENT_IMAGE: custom/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    depends_on:
      - msc_custom

  fibonacci:
    image: custom/softwareag/msc-fibonacci:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
      args:
        PARENT_IMAGE: custom/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: ${SAG_HOME}
        MSC_INSTANCE_NAME: default
    depends_on:
      - msc_custom