version: "3.0"

networks:
  sagdemoruntime:
    external: true

services:

  msc_apimashup_userfull_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_apimashup_userfull:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.apimashup.userfull
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5556:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap
      - msc_iplocator_1
      - msc_userinfo_1
      - msc_fibonacci_1

  msc_userinfo_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_userinfo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userinfo
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5558:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap
      - msc_randomutils_1

  msc_iplocator_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_iplocator:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.iplocator
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5557:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  msc_fibonacci_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_fibonacci:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5559:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  msc_randomutils_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_randomutils:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.randomutils
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5560:5555"
    environment:
      - registry_activate=true
    networks:
      - sagdemoruntime
    depends_on:
      - consul-server-bootstrap

  consul-agent-1: &consul-agent
    image: consul:1.2.3
    networks:
      - sagdemoruntime
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"