version: "3.0"

services:

  msc:
    image: ${REGISTRY}custom/softwareag/webmethods-microservicescontainer:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.msc.custom
      args:
        SAG_HOME: ${SAG_HOME}

  iplocator:
    image: ${REGISTRY}softwareag/iplocator:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.iplocator
    depends_on:
      - msc

  userinfo:
    image: ${REGISTRY}softwareag/userinfo:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.userinfo
    depends_on:
      - msc

  userservice:
    image: ${REGISTRY}softwareag/userservice:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.userservice
    depends_on:
      - msc

  fibonacci:
    image: ${REGISTRY}softwareag/fibonacci:${TAG}-msc
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
    depends_on:
      - msc