version: "3.0"

networks:
  sagdemoruntime:
    external: true

services:
  msc_apimashup_userfull_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_apimashup_userfull:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.apimashup.userfull
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5556:5555"
    environment:
      - registry_activate=false
      - api_hostlookup_userinfo=msc_userinfo_1:5555
      - api_hostlookup_iplocator=msc_iplocator_1:5555
      - api_hostlookup_fibonacci=msc_fibonacci_1:5555
    networks:
      - sagdemoruntime
    depends_on:
      - msc_iplocator_1
      - msc_userinfo_1
      - msc_fibonacci_1

  msc_iplocator_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_iplocator:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.iplocator
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5557:5555"
    environment:
      - registry_activate=false
    networks:
      - sagdemoruntime

  msc_userinfo_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_userinfo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.userinfo
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5558:5555"
    environment:
      - registry_activate=false
      - api_hostlookup_randomutils=msc_randomutils_1:5555
    networks:
      - sagdemoruntime
    depends_on:
      - msc_randomutils_1

  msc_fibonacci_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_fibonacci:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.fibonacci
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5559:5555"
    environment:
      - registry_activate=false
    networks:
      - sagdemoruntime

  msc_randomutils_1:
    image: ${REG}softwareag_custom/sag-microservice-demo_randomutils:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.randomutils
      args:
        PARENT_IMAGE: store/softwareag/webmethods-microservicesruntime:${TAG}
        SAG_HOME: /opt/softwareag
        MSC_INSTANCE_NAME: default
    ports:
      - "5560:5555"
    environment:
      - registry_activate=false
    networks:
      - sagdemoruntime