---
swagger: "2.0"
info:
  version: "1.0"
  title: "UserFull"
host: "7435b6fdcadb:5555"
basePath: "/restv2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /userdetails/{userId}:
    get:
      operationId: "userdetailsuserId_GET_1"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
