---
swagger: "2.0"
info:
  version: "1.0"
  title: "fibonacci"
host: "fibonacci.docker.tests:5555"
basePath: "/restv2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /NextNumber/{number}:
    get:
      operationId: "NextNumbernumber_GET_1"
      parameters:
      - name: "number"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/NextNumbernumber_GET_response"
        401:
          description: "Access Denied"
definitions:
  NextNumber/{number}_GET_$response:
    required:
    - "fibonachiNumber"
    properties:
      fibonachiNumber:
        type: "string"
