---
swagger: "2.0"
info:
  version: "1.0"
  title: "IpLocator"
host: "e0fd6418b869:5555"
basePath: "/restv2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /iplocator/{ip}:
    get:
      operationId: "iplocatorip_GET_1"
      parameters:
      - name: "ip"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/iplocatorip_GET_response"
        401:
          description: "Access Denied"
definitions:
  ipLocator: {}
  iplocatorip_GET_response:
    required:
    - "ipLocator"
    properties:
      ipLocator:
        $ref: "#/definitions/ipLocator"
