---
swagger: "2.0"
info:
  version: "1.0"
  title: "GenerateRandom"
host: "68851fd09a40:5555"
basePath: "/restv2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /generateRandom/number/{max}:
    get:
      operationId: "generateRandomnumbermax_GET_1"
      parameters:
      - name: "max"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomnumbermax_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/numeric/{length}:
    get:
      operationId: "generateRandomnumericlength_GET_2"
      parameters:
      - name: "length"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomnumericlength_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/lastname:
    get:
      operationId: "generateRandomlastname_GET_3"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomlastname_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/firstname:
    get:
      operationId: "generateRandomfirstname_GET_4"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomfirstname_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/ipv4:
    get:
      operationId: "generateRandomipv4_GET_5"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomipv4_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/text/{length}:
    get:
      operationId: "generateRandomtextlength_GET_6"
      parameters:
      - name: "length"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomtextlength_GET_response"
        401:
          description: "Access Denied"
  /generateRandom/ssn:
    get:
      operationId: "generateRandomssn_GET_7"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/generateRandomssn_GET_response"
        401:
          description: "Access Denied"
definitions:
  generateRandomlastname_GET_response:
    required:
    - "lastName"
    properties:
      lastName:
        type: "string"
  generateRandomipv4_GET_response:
    required:
    - "ipv4"
    properties:
      ipv4:
        type: "string"
  generateRandomnumericlength_GET_response:
    required:
    - "numeric"
    properties:
      numeric:
        type: "string"
  generateRandomtextlength_GET_response:
    required:
    - "text"
    properties:
      text:
        type: "string"
  generateRandomnumbermax_GET_response:
    required:
    - "number"
    properties:
      number:
        type: "integer"
        format: "int32"
  generateRandomssn_GET_response:
    required:
    - "ssn"
    properties:
      ssn:
        type: "string"
  generateRandomfirstname_GET_response:
    required:
    - "firstName"
    properties:
      firstName:
        type: "string"
