---
swagger: "2.0"
info:
  version: "1.0"
  title: "UserInfo"
host: "e0fd6418b869:5555"
basePath: "/restv2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /userinfo/{userId}:
    get:
      operationId: "userinfouserId_GET_1"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/userinfouserId_GET_response"
        401:
          description: "Access Denied"
  /userinfo:
    get:
      operationId: "userinfo_GET_2"
      parameters:
      - name: "userId"
        in: "formData"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/userinfo_GET_response"
        401:
          description: "Access Denied"
definitions:
  userinfo_GET_response:
    required:
    - "UserRecord"
    properties:
      UserRecord:
        $ref: "#/definitions/UserRecord"
  userinfouserId_GET_response:
    required:
    - "UserRecord"
    properties:
      UserRecord:
        $ref: "#/definitions/UserRecord"
  UserRecord:
    required:
    - "favNumber"
    - "firstName"
    - "ip"
    - "lastName"
    - "otherText1"
    - "otherText2"
    - "userId"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      otherText2:
        type: "string"
      otherText1:
        type: "string"
      ip:
        type: "string"
      favNumber:
        type: "string"
      userId:
        type: "string"
